name = "HierarchicalUtils"
uuid = "f9ccea15-0695-44b9-8113-df7c26ae4fa9"
authors = ["Simon Mandlik <simon.mandlik@gmail.com>"]
version = "0.0.8"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
Setfield = "0.6"
DataStructures = "0.17"
julia = "1.4"
