name = "HierarchicalUtils"
uuid = "f9ccea15-0695-44b9-8113-df7c26ae4fa9"
authors = ["Simon Mandlik <simon.mandlik@gmail.com>"]
version = "0.1.0"

[deps]
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
